// Pick up from language name and color https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

export const languageColors = [
  { name: "C", color: "#555555" },
  { name: "C#", color: "#178600" },
  { name: "C++", color: "#f34b7d" },
  { name: "CSS", color: "#563d7c" },
  { name: "Dart", color: "#00b4ab" },
  { name: "Elixir", color: "#6e4a7e" },
  { name: "Go", color: "#00add8" },
  { name: "HTML", color: "#e34c26" },
  { name: "Java", color: "#b07219" },
  { name: "JavaScript", color: "#f1e05a" },
  { name: "Julia", color: "#a270ba" },
  { name: "Kotlin", color: "#a97bff" },
  { name: "PHP", color: "#4f5d95" },
  { name: "Perl", color: "0298c3" },
  { name: "Python", color: "#3572a5" },
  { name: "Ruby", color: "#701516" },
  { name: "Rust", color: "#dea584" },
  { name: "SCSS", color: "#c6538c" },
  { name: "Scala", color: "#c22d40" },
  { name: "Svelte", color: "#ff3e00" },
  { name: "Swift", color: "#ffac45" },
  { name: "TypeScript", color: "#2b7489" },
  { name: "Vue", color: "#41b883" },
  { name: "WebAssembly", color: "#04133b" },
];
